# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastPDist <- function(Ar, Br) {
    .Call('_scPharm_fastPDist', PACKAGE = 'scPharm', Ar, Br)
}

SparseMCAStep1 <- function(X) {
    .Call('_scPharm_SparseMCAStep1', PACKAGE = 'scPharm', X)
}

MCAStep2 <- function(Z, V, Dc) {
    .Call('_scPharm_MCAStep2', PACKAGE = 'scPharm', Z, V, Dc)
}

